import React,{useState}from'react';import{createRoot}from'react-dom/client';import{createPortal}from'react-dom';import{ArrowLeft,ArrowRight,Check,ChevronDown,Menu,Target,Volume2,VolumeX,X}from'lucide-react';import'./styles.css';
const A='./assets/';
const tabs=['The evidence','The enabler','Three layers','Named duty','Exam lens'];
const layers=[
['International Standards','06-international-standard.png','The ISO family and its peers — generic, certifiable management-system frameworks. ISO 9001 for quality management systems. ISO/IEC 27001 for information security. ISO 25010 for software product quality characteristics. Broad frameworks applicable across many industries, with formal certification available.'],
['Industry and Regulatory Standards','07-regulatory-standard.png','Sector-specific, and frequently legally or contractually mandatory rather than optional best practice. Example: PCI-DSS governs how any organization handling credit card data must secure that data — it isn\'t a suggestion, it\'s a condition of being allowed to process card payments at all. Allergen labeling requirements in food production work the same way — specific, sector-bound, enforced with real penalties for non-compliance.'],
['Organizational Standards','08-organizational-standard.png','The company\'s own internal policies, procedures, and guidelines — the Organizational Process Assets covered in earlier lessons. A secure-coding standard. Defined release gates a deliverable must pass before shipping. Brand and UX guidelines. The shared Definition of Done a team charter established.']];
const duties=[
['Name Each Applicable Regulation in the Plan','11-name-regulation.png','Not a vague reference to "relevant regulations" — the specific regulation, named explicitly, so there\'s no ambiguity about what the project is actually required to meet.'],
['Trace It to the Deliverables and Processes It Constrains','12-trace-deliverables.png','A named regulation that isn\'t linked to the specific deliverable it governs is just a citation sitting in a document — it needs to be connected to exactly what part of the project it actually restricts.'],
['Assign an Owner','13-assign-owner.png','Someone specific is accountable for that regulation\'s compliance — not the project team collectively, which in practice means no one individually.'],
['Decide How Conformance Will Be Evidenced','14-conformance-evidence.png','This turns "we\'re compliant" from a claim into something demonstrable — a specific test result, a signed checklist, an audit log, a certification document. Compliance without evidence is indistinguishable from non-compliance the moment an actual auditor asks for proof.'],
['Wire Nonconformance Procedures Before Failure Occurs','15-nonconformance-response.png','What happens the moment a compliance check fails needs to be decided in advance — not improvised in a panic once a regulator or auditor has already found the gap.']];
const modalData={
hook:{title:'Project quality works exactly the same way.',image:'02-compliance-duty-modal.png',text:'Believing the project is compliant isn\'t compliance. This lesson is about turning regulatory obligation from an ambient hope into a named, owned, evidenced duty — one that survives an audit, not just a conversation.'},
enabler:{title:'Help Ensure Regulatory Compliance',image:'04-enabler-modal.png',text:'This enabler — ECO Process Task 7\'s "help ensure regulatory compliance" — makes one specific layer of the quality management plan\'s standards stack a named project manager responsibility. The quality management plan\'s first listed component is the quality standards the project will use — and in practice, those standards arrive in three distinct layers.'},
layerExample:{title:'Worked example',image:'09-healthcare-example.png',text:'A healthcare software project might sit inside all three layers at once — pursuing ISO 27001 certification for its information security management (international), required to meet HIPAA\'s specific data-handling rules (industry/regulatory), while also following the company\'s own internal code review standard before any release (organizational). Missing any one of the three layers leaves a real gap, even if the other two are handled well.'},
dutyExample:{title:'Worked example',image:'16-fintech-example.png',text:'A fintech project handling card payments might name PCI-DSS explicitly in the quality management plan, trace it specifically to the payment processing module and the data storage layer, assign the security lead as owner, decide that conformance will be evidenced through a documented quarterly vulnerability scan and an annual third-party audit report, and define in advance that any failed scan triggers an immediate freeze on payment processing changes until the vulnerability is resolved and re-scanned. The quality management plan\'s own definition backs this up precisely: it describes how policies, procedures, and guidelines will be implemented — implementation, not citation. Listing PCI-DSS in a document isn\'t compliance. Tracing it, owning it, and evidencing it is.'},
exam:{title:'Help Ensure Regulatory Compliance',image:'18-exam-synthesis.png',text:'The standards stack runs three layers deep: international standards like ISO provide generic, certifiable frameworks; industry and regulatory standards like PCI-DSS or allergen labeling are sector-specific and often legally mandatory; and organizational standards capture the company\'s own internal policies and guidelines. ECO 7.4 makes the middle layer a named, owned, evidenced duty — trace each applicable regulation to the deliverables it governs, assign a real owner, decide in advance how conformance will be proven, and wire the response to failure before failure ever happens. A regulation cited in a plan but never implemented isn\'t compliance. It\'s a sentence waiting for an auditor to ask the question it can\'t answer.',bullets:['Three-layer standards stack: international (ISO, certifiable frameworks), industry/regulatory (PCI-DSS, allergen labeling — often legally mandatory), organizational (internal policies, Definition of Done)','ECO 7.4 makes the middle layer a named PM responsibility, operationalized in five steps','Five steps: name the regulation, trace it to deliverables, assign an owner, decide how conformance is evidenced, wire nonconformance procedures in advance','A regulation merely cited — with no trace, owner, or evidence — is not compliance; it\'s a citation waiting to fail an audit']}};
function Modal({d,close,read}){const[step,setStep]=useState(0);const memory=d.bullets&&step===1;return createPortal(<div className="modal-backdrop" onClick={close}><section className="focus-modal" onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><X/></button>{!memory&&<><img className="modal-illustration" src={A+d.image}/><h3>{d.title}</h3><div className="modal-copy"><p>{d.text}</p></div></>}{memory&&<div className="memory-step"><p className="eyebrow">EXAM-RELEVANT ENABLERS TO REMEMBER</p><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}{d.bullets&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{read();close()}}>Mark as read <Check/></button>}</section></div>,document.body)}
const quiz={q:'Scenario: A project\'s quality management plan lists "the project will comply with PCI-DSS" as a single line item, with no further detail. During an external audit, the auditor asks which specific deliverables are governed by PCI-DSS, who owns compliance for each, and what evidence exists proving the requirements were actually met. What does this situation best illustrate?',a:['The project is compliant, since PCI-DSS was named in the quality management plan','The gap between citing a regulation and actually implementing compliance against it — tracing, ownership, and evidence were never established','The auditor is being unreasonable by expecting more detail than a compliance citation','ISO 9001 certification should have been pursued instead of PCI-DSS'],good:'Correct! This is exactly the failure ECO 7.4 is built to prevent. A named regulation with no trace to specific deliverables, no assigned owner, and no evidence of conformance is a citation, not implementation — and an auditor asking these exact questions is confirming that gap directly.',bad:'Reconsider — naming a regulation is only the first of five steps; these audit questions are exactly what any credible audit should ask; and this scenario isn\'t about choosing the wrong standard, it\'s about failing to implement the correct one already identified.'};
function Quiz({finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{quiz.q}</h3><div className="answers vertical">{quiz.a.map((x,i)=><button key={x} onClick={()=>setP(i)} className={p===i?(i===1?'correct':'wrong'):''}><span>{'ABCD'[i]}</span>{x}</button>)}</div>{p!==null&&<><p className={`feedback ${p===1?'good':'bad'}`}>{p===1?quiz.good:quiz.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
function App(){const[s,setS]=useState(0),[done,setDone]=useState([false,false,false,false,false]),[modal,setModal]=useState(null),[quizOpen,setQuizOpen]=useState(false),[seenLayers,setSeenLayers]=useState([]),[seenDuties,setSeenDuties]=useState([]),[sound,setSound]=useState(true),[outline,setOutline]=useState(false);const mark=i=>setDone(v=>v.map((x,n)=>n===i?true:x));const go=i=>{if(i>=0&&i<5&&(i===0||done[i-1]))setS(i)};const openLayer=i=>{setSeenLayers(v=>v.includes(i)?v:[...v,i]);setModal({title:layers[i][0],image:layers[i][1],text:layers[i][2],detail:true})};const openDuty=i=>{setSeenDuties(v=>v.includes(i)?v:[...v,i]);setModal({title:duties[i][0],image:duties[i][1],text:duties[i][2],detail:true})};return <div className="app"><header><button className="course" onClick={()=>setOutline(!outline)}><Menu/> Project Management Professional <ChevronDown/></button><div className="dots">{Array.from({length:10},(_,i)=><span key={i} className={i<8?'past':i===8?'current':''}>{i<8&&<Check/>}</span>)}</div><div className="tools"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}{sound?'Sound on':'Sound off'}</button><button>Quit</button></div></header><div className="section-label">SECTION {s+1} OF 5</div><nav>{tabs.map((t,i)=><button key={t} onClick={()=>go(i)} disabled={i>0&&!done[i-1]} className={i===s?'active':done[i]?'complete':''}>{done[i]&&<Check/>}{t}</button>)}</nav><main>
{s===0&&<section className="hero"><div><p className="eyebrow">LESSON 4.8.3</p><h1>Help Ensure Regulatory Compliance</h1><p>Think about a restaurant's kitchen. It might genuinely serve delicious food — but if the health inspector shows up and finds no documented handwashing procedure, no record of refrigerator temperature checks, and no allergen labeling on the menu, none of that good cooking matters. Compliance isn't measured by good intentions. It's measured by evidence — a specific record, produced on demand, proving a specific requirement was actually met.</p><button className="primary" onClick={()=>setModal(modalData.hook)}>Reveal the compliance gap <ArrowRight/></button></div><img src={A+'01-kitchen-hook.png'}/></section>}
{s===1&&<section className="hero"><div><h2>What This Enabler Means</h2><p>This enabler zooms in on one specific layer of the quality management plan's standards — and makes it a named responsibility nobody can quietly assume is somebody else's job.</p><button className="primary" onClick={()=>setModal(modalData.enabler)}>Reveal the named responsibility <ArrowRight/></button></div><img src={A+'03-standards-stack-screen.png'}/></section>}
{s===2&&<section className="components"><p className="eyebrow">THE THREE-LAYER STANDARDS STACK</p><h2>Standards don't all come from the same place, and they don't all carry the same weight.</h2><p>Click each layer to explore.</p><img className="wide-illustration" src={A+'05-three-layers-overview.png'}/><div className="component-grid three">{layers.map((c,i)=><button key={c[0]} onClick={()=>openLayer(i)} className={seenLayers.includes(i)?'seen':''}><span>{String(i+1).padStart(2,'0')}</span><strong>{c[0]}</strong><ArrowRight/></button>)}</div>{seenLayers.length===3&&<button className="primary centered" onClick={()=>setModal(modalData.layerExample)}>Open the worked example <ArrowRight/></button>}</section>}
{s===3&&<section className="components"><p className="eyebrow">FROM CITATION TO IMPLEMENTATION</p><h2>ECO 7.4 makes the middle layer — industry and regulatory standards — an explicit project manager responsibility.</h2><p>Operationally, that breaks into five concrete steps. Click each to explore.</p><img className="wide-illustration" src={A+'10-five-step-overview.png'}/><div className="component-grid">{duties.map((c,i)=><button key={c[0]} onClick={()=>openDuty(i)} className={seenDuties.includes(i)?'seen':''}><span>{String(i+1).padStart(2,'0')}</span><strong>{c[0]}</strong><ArrowRight/></button>)}</div>{seenDuties.length===5&&<button className="primary centered" onClick={()=>setModal(modalData.dutyExample)}>Open the worked example <ArrowRight/></button>}</section>}
{s===4&&<section className="hero"><div><p className="eyebrow">EXAM LENS</p><h2>Back to that kitchen one more time — because the inspector was never going to be satisfied by how the food tasted.</h2><button className="primary" onClick={()=>setModal(modalData.exam)}>Reveal the exam lens <ArrowRight/></button></div><img src={A+'17-kitchen-complete.png'}/></section>}
</main><footer><button onClick={()=>go(s-1)} disabled={s===0}><ArrowLeft/> Previous</button><button className="continue" onClick={()=>go(s+1)} disabled={!done[s]||s===4}>{s===4?'Complete':'Continue'} <ArrowRight/></button></footer>{modal&&<Modal d={modal} close={()=>setModal(null)} read={()=>{if(modal.detail)return;if(modal===modalData.layerExample){mark(2)}else if(modal===modalData.dutyExample){setQuizOpen(true)}else mark(s)}}/>}{quizOpen&&<Quiz finish={()=>{setQuizOpen(false);mark(3)}}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
